@server_HostAddress = http://localhost:5240/api

### Сброс базы и заполнение демо-данными (DEBUG)
GET {{server_HostAddress}}/reset
Accept: application/json

###

### Регистрация
POST {{server_HostAddress}}/auth/register
Content-Type: application/json

{
  "name": "Нұрлан Серікұлы",
  "email": "admin@example.com",
  "password": "123456"
}

###

### Логин
POST {{server_HostAddress}}/auth/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "123456"
}

###

### Курсы
GET {{server_HostAddress}}/courses
Accept: application/json

###

### Курс по ID
GET {{server_HostAddress}}/courses/2
Accept: application/json

###

### Поиск курсов
GET {{server_HostAddress}}/courses/search?query=react
Accept: application/json

###

### Категории
GET {{server_HostAddress}}/categories
Accept: application/json

###

### Отзывы курса
GET {{server_HostAddress}}/reviews/course/2
Accept: application/json
